/*Деница Миткова Метова фак.номер-1901321073*/

CREATE TABLE CARS
(
CAR_ID INT PRIMARY KEY,
MODEL NVARCHAR(100) NOT NULL,
COLOR NVARCHAR(20) NOT NULL
)

CREATE TABLE CLIENT
(
CLIENT_ID INT PRIMARY KEY,
FIRSTNAME NVARCHAR(50) NOT NULL,
LASTNAME NVARCHAR(50) NOT NULL,
CITY NVARCHAR(50) NULL,
PHONE VARCHAR(20) NULL
)

CREATE TABLE OFFER
(
CAR_ID INT FOREIGN KEY REFERENCES CARS(CAR_ID),
CLIENT_ID INT FOREIGN KEY REFERENCES CLIENT(CLIENT_ID),
PRICE DECIMAL(8,2) NOT NULL,
CONSTRAINT PKYC PRIMARY KEY (CAR_ID, CLIENT_ID)
)

ALTER TABLE CARS
ADD YEAR DATE

INSERT INTO CARS(CAR_ID, MODEL, COLOR)
VALUES('203', 'BMW', 'черен')

SELECT * FROM CARS

INSERT INTO CLIENT(CLIENT_ID, FIRSTNAME, LASTNAME, CITY, PHONE)
VALUES('123', 'Иван', 'Иванов', 'София', '0888108076')

SELECT * FROM CLIENT

INSERT INTO OFFER(CAR_ID, CLIENT_ID, PRICE)
VALUES('203', '123', '8590.99')

SELECT * FROM OFFER

UPDATE OFFER
SET PRICE = '7900.00'
WHERE CAR_ID = 2 AND CLIENT_ID = 1

SELECT FIRSTNAME, LASTNAME, CITY, MODEL, PRICE
FROM CLIENT C JOIN OFFER O ON C.CLIENT_ID = O.CLIENT_ID
              JOIN CARS CA ON O.CAR_ID = CA.CAR_ID
ORDER BY FIRSTNAME, LASTNAME DESC


SELECT MODEL, COLOR, FIRSTNAME, LASTNAME, PRICE
FROM CARS C LEFT OUTER JOIN OFFER O ON C.CAR_ID = O.CAR_ID
            JOIN CLIENT CL ON O.CLIENT_ID = CL.CLIENT_ID
ORDER BY MODEL

CREATE VIEW CAR_VIEW
AS
SELECT MODEL, SUM(PRICE) PRICE
FROM CARS C JOIN OFFER O
ON C.CAR_ID = O.CAR_ID
GROUP BY MODEL
HAVING SUM(PRICE) > 5000

SELECT * FROM CAR_VIEW

